/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.14 (master-db54337a6) - 29 Jul 2019 10:54
*/

/*
  Differentiation of xTATx in forward (tangent) mode:
   variations   of useful results: *out
   with respect to varying inputs: *A
   RW status of diff variables: *out:out *A:in
   Plus diff mem management of: out:in A:in
*/
void xTATx_d(float *x, float *A, float *Ad, float *out, float *outd, int N) {
    int i, j, k;
    float *ATA;
    float *ATAd;
    ATAd = (float *)malloc(sizeof(float)*N*N);
    ATA = (float *)malloc(sizeof(float)*N*N);
    float *tmp;
    float *tmpd;
    tmpd = (float *)malloc(sizeof(float)*N);
    tmp = (float *)malloc(sizeof(float)*N);
    /* ATA = A^T * A */
    for (i = 0; i < N; ++i)
        for (j = 0; j < N; ++j) {
            ATAd[i*N + j] = 0.0;
            ATA[i*N + j] = 0;
            for (k = 0; k < N; ++k) {
                /* A^T[i * N + k] -> A[k * N + i] */
                ATAd[i*N + j] = ATAd[i*N + j] + Ad[k*N+i]*A[k*N+j] + A[k*N+i]*
                    Ad[k*N+j];
                ATA[i*N + j] += A[k*N+i]*A[k*N+j];
            }
        }
    /* tmp = ATA * x */
    for (i = 0; i < N; ++i) {
        tmpd[i] = 0.0;
        tmp[i] = 0;
        for (j = 0; j < N; ++j) {
            tmpd[i] = tmpd[i] + x[j]*ATAd[N*i+j];
            tmp[i] += ATA[N*i+j]*x[j];
        }
    }
    /* out = x^T * tmp */
    *outd = 0.0;
    *out = 0;
    *outd = 0.0;
    for (i = 0; i < N; ++i) {
        *outd = *outd + x[i]*tmpd[i];
        *out += x[i]*tmp[i];
    }
    free(tmpd);
    free(tmp);
    free(ATAd);
    free(ATA);
}
