/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.14 (master-db54337a6) - 29 Jul 2019 10:54
*/
/* xTAx computes x^T A x
 * We want to differentiate with x
 * */

/*
  Differentiation of xTAx in forward (tangent) mode:
   variations   of useful results: *out
   with respect to varying inputs: *x
   RW status of diff variables: *out:out *x:in
   Plus diff mem management of: out:in x:in
*/
void xTAx_d(float *x, float *xd, float *A, float *out, float *outd, int N) {
    int i, j, k;
    float *tmp;
    float *tmpd;
    tmpd = (float *)malloc(sizeof(float)*N);
    tmp = (float *)malloc(sizeof(float)*N);
    /* tmp = A * x */
    for (i = 0; i < N; ++i) {
        tmpd[i] = 0.0;
        tmp[i] = 0;
        for (j = 0; j < N; ++j) {
            tmpd[i] = tmpd[i] + A[N*i+j]*xd[j];
            tmp[i] += A[N*i+j]*x[j];
        }
    }
    /* out = x^T * tmp */
    *outd = 0.0;
    *out = 0;
    *outd = 0.0;
    for (i = 0; i < N; ++i) {
        *outd = *outd + xd[i]*tmp[i] + x[i]*tmpd[i];
        *out += x[i]*tmp[i];
    }
    free(tmpd);
    free(tmp);
}
