/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.14 (master-db54337a6) - 29 Jul 2019 10:54
*/
#include <adBuffer.h>
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.14 (master-db54337a6) - 29 Jul 2019 10:54

 xTAx computes x^T A x
 * We want to differentiate with x
 * */
int N = 100;

/*
  Differentiation of xTAx_d in reverse (adjoint) mode:
   gradient     of useful results: alloc(*tmp) alloc(*tmpd) *out
                *xd *x *outd *A
   with respect to varying inputs: alloc(*tmp) alloc(*tmpd) *out
                *xd *x *outd *A
   RW status of diff variables: alloc(*tmp):in-out alloc(*tmpd):in-out
                *out:in-out *xd:incr *x:incr *outd:in-out *A:incr
   Plus diff mem management of: out:in xd:in x:in outd:in A:in


  Differentiation of xTAx in forward (tangent) mode:
   variations   of useful results: *out
   with respect to varying inputs: *x
   RW status of diff variables: *out:out *x:in
   Plus diff mem management of: out:in x:in
*/
void xTAx_d_b(float *x, float *xb, float *xd, float *xdb, float *A, float *Ab,
        float *out, float *outb, float *outd, float *outdb) {
    int i, j, k;
    float *tmp;
    float *tmpb;
    float *tmpd;
    float *tmpdb;
    int ii1;
    tmpdb = (float *)malloc(sizeof(float)*N);
    for (ii1 = 0; ii1 < N; ++ii1)
        tmpdb[ii1] = 0.0;
    tmpd = (float *)malloc(sizeof(float)*N);
    tmpb = (float *)malloc(sizeof(float)*N);
    for (ii1 = 0; ii1 < N; ++ii1)
        tmpb[ii1] = 0.0;
    tmp = (float *)malloc(sizeof(float)*N);
    /* tmp = A * x */
    for (i = 0; i < N; ++i) {
        tmpd[i] = 0.0;
        tmp[i] = 0;
        for (j = 0; j < N; ++j) {
            tmpd[i] = tmpd[i] + A[N*i+j]*xd[j];
            tmp[i] = tmp[i] + A[N*i+j]*x[j];
        }
    }
    for (i = N-1; i > -1; --i) {
        xb[i] = xb[i] + tmp[i]*(*outb);
        tmpb[i] = tmpb[i] + x[i]*(*outb);
        xdb[i] = xdb[i] + tmp[i]*(*outdb);
        tmpb[i] = tmpb[i] + xd[i]*(*outdb);
        xb[i] = xb[i] + tmpd[i]*(*outdb);
        tmpdb[i] = tmpdb[i] + x[i]*(*outdb);
    }
    *outdb = 0.0;
    *outb = 0.0;
    *outdb = 0.0;
    for (i = N-1; i > -1; --i) {
        for (j = N-1; j > -1; --j) {
            Ab[N*i + j] = Ab[N*i + j] + x[j]*tmpb[i];
            xb[j] = xb[j] + A[N*i+j]*tmpb[i];
            Ab[N*i + j] = Ab[N*i + j] + xd[j]*tmpdb[i];
            xdb[j] = xdb[j] + A[N*i+j]*tmpdb[i];
        }
        tmpb[i] = 0.0;
        tmpdb[i] = 0.0;
    }
    free(tmp);
    free(tmpb);
    free(tmpd);
    free(tmpdb);
}
